version: "3"

services:
   repair-service:
      image: repair-service
      container_name: repair-service
      networks:
         - micro-service-network
      ports:
        - "8081:8081"
      build: ./repair-service
         
   housing-service:
      image: housing-service
      container_name: housing-service
      networks:
         - micro-service-network
      ports:
         - "8080:8080"
      environment:
         WAIT_HOSTS: repair-service:8081
      build: ./housing-service

networks:
    micro-service-network: