apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: housing-service
    provider: jkube
    group: ${project.groupId}
  name: housing-service
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    app: housing-service
    provider: jkube
    group: ${project.groupId}
  strategy:
    rollingParams:
      timeoutSeconds: 3600
    type: Rolling
  template:
    metadata:
      labels:
        app: housing-service
        provider: jkube
        group: ${project.groupId}
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: housing-service
      containers:
      - name: housing-service
        volumeMounts:
          - name: config-volume
            mountPath: /deployments/application.properties
            subPath: application.properties
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - housing-service
      from:
        kind: ImageStreamTag
        name: housing-service:${project.version}
    type: ImageChange
